name: Deploy Doctel WebService App

on:
  push:
    branches:
      - master  # branch 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            
            # Navigate to the project directory
            cd ${{ secrets.PROJECT_PATH }} || exit 1

            # Ensure we are on the correct branch
            git checkout master
            git pull origin master

            # Install dependencies
            npm install --production

            # Restart the application with PM2
            pm2 restart "doctel-server-node" || pm2 start npm --name "doctel-server-node" -- start
          EOF
